/** 休業・貸切の契約。POST previewも閲覧のみの人には許可しない。 */
const string={type:'string'},date={type:'string',format:'date'},integer={type:'integer',minimum:1};
const properties={storeId:string,startDate:date,endDate:date,allDay:{type:'boolean'},startTime:{type:['string','null'],description:'HH:MM。終日ならnull'},endTime:{type:['string','null'],description:'HH:MM（終了のみ24:00可）'},kind:{type:'string',enum:['temporary_closed','private_event','maintenance','other']},memo:{type:['string','null'],maxLength:1000},tableIds:{type:'array',items:string,uniqueItems:true,description:'省略または空配列は全卓'}};
const required=['storeId','startDate','endDate','allDay','kind'];
const closure={type:'object',properties:{...properties,id:string,version:integer,createdBy:{type:['string','null']},createdByName:{type:['string','null']},createdAt:string,updatedAt:string}};
const preview={type:'object',properties:{reservations:{type:'array',items:{type:'object',properties:{id:string,startsAt:string,endsAt:string,guestCount:integer,customerName:string,source:string,tableId:{type:['string','null']},friendId:{type:['string','null']},isLineFriend:{type:'boolean'}}}},waitlistCount:{type:'integer',minimum:0},conflicts:{type:'array',items:closure}}};
const account={name:'account_id',in:'query',required:true,schema:string},store={name:'storeId',in:'query',required:true,schema:string},id={name:'id',in:'path',required:true,schema:string};
function response(schema:unknown,description:string){return {description,content:{'application/json':{schema}}};}
const errors={'400':{description:'過去日・形式・卓の所属が不正'},'401':{description:'認証が必要'},'403':{description:'権限・店舗の範囲が不足'},'404':{description:'対象がありません'},'409':response({type:'object',properties:{error:string,code:string,currentVersion:integer,reason:string,...preview.properties}},'closure_overlap（conflictsで重なる記録を返す）・version_conflict・closure_conflict')};
function op(summary:string,parameters:unknown[],body?:unknown,result?:unknown){return {tags:['Restaurant'],summary,security:[{bearerAuth:[]}],parameters,...(body?{requestBody:{required:true,content:{'application/json':{schema:body}}}}:{}),responses:{'200':response(result??{type:'object'},'成功'),...errors}};}
const input={type:'object',properties,required};
const success=(data:unknown)=>({type:'object',properties:{success:{type:'boolean',const:true},data}});
export const restaurantClosurePaths={
 '/api/restaurant-test/closures':{get:op('休業・貸切を読む（閲覧のみ可）',[account,store,{name:'month',in:'query',schema:{type:'string',pattern:'^\\d{4}-\\d{2}$'}}],undefined,success({type:'array',items:closure})),post:{...op('休業・貸切を保存。既存予約は取り消さず、媒体ごとに閉じる作業を作る',[account],input,success({type:'object',properties:{closure,...preview.properties}})),responses:{'201':response(success({type:'object',properties:{closure,...preview.properties}}),'保存'),...errors}}},
 '/api/restaurant-test/closures/preview':{post:op('保存せずに重なる予約と待機件数を読む',[account],input,success(preview))},
 '/api/restaurant-test/closures/{id}':{patch:op('入力全体と読み込んだ版で変更',[account,id],{...input,properties:{...properties,expectedVersion:integer},required:[...required,'expectedVersion']},success({type:'object',properties:{closure,...preview.properties}})),delete:op('版を検査して履歴へ移し、媒体ごとに開けてよい作業を残す',[account,id],{type:'object',required:['expectedVersion'],properties:{expectedVersion:integer}},success({type:'object',properties:{id:string,version:integer,archived:{type:'boolean',const:true}}}))},
 '/api/restaurant-test/availability':{get:op('閉じた卓・予約・仮押さえ・待機招待を除いた空き卓',[account,store,...['startsAt','endsAt','guestCount'].map(name=>({name,in:'query',required:true,schema:name==='guestCount'?integer:string}))])},
 '/api/liff/booking/seat-availability':{get:{...op('LINE本人確認後に自店の空き卓だけ返す。休業メモは公開しない',[{name:'Authorization',in:'header',required:true,schema:string,description:'Bearer <LINE ID token>。ルート内で本人を検証'}, {name:'liffId',in:'query',required:true,schema:string},...['store_id','starts_at','ends_at','guest_count'].map(name=>({name,in:'query',required:true,schema:name==='guest_count'?integer:string}))]),security:[]}},
 '/api/restaurant-test/google/hours/from-closure':{post:op('休業・貸切からGoogle特別営業時間の案だけ作る。送信は既存の確認手順',[account],{type:'object',required:['closureId','expectedVersion'],properties:{closureId:string,expectedVersion:integer,includePrivateEvent:{type:'boolean',default:false}}})},
};
