// @vitest-environment happy-dom
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { useState } from 'react'
import TagPickerField from './tag-picker-field'
import TapExtrasField from './tap-extras-field'
const mocks = vi.hoisted(() => ({ list: vi.fn(), groups: vi.fn(), create: vi.fn() }))
vi.mock('@/lib/api', () => ({ api: { tags: { list: mocks.list, create: mocks.create }, tagGroups: { list: mocks.groups } } }))
vi.mock('@/lib/use-admin-theme', () => ({ useAdminTheme: () => 'v8' }))
vi.mock('./use-tap-action-sources', () => ({ useTapActionAccount: () => null }))
const tags = [{ id: 't1', name: '予約に興味', groupId: 'g1', isStarred: true }, { id: 't2', name: '来店', groupId: null }]
beforeEach(() => {
  mocks.list.mockResolvedValue({ success: true, data: tags })
  mocks.groups.mockResolvedValue({ success: true, data: [{ id: 'g1', name: '興味', color: '#087a3e' }] })
  mocks.create.mockResolvedValue({ success: true, data: { id: 'new', name: '新しいタグ', groupId: null } })
})
afterEach(() => { cleanup(); vi.clearAllMocks() })
async function open() {
  fireEvent.click(screen.getByRole('button', { name: 'タグを付ける：変える' }))
  await screen.findByRole('checkbox', { name: '予約に興味', exact: true })
  return within(screen.getByRole('dialog'))
}
test('欄全体で窓を開き、フォルダ・検索で絞って複数選択する。キャンセルは保存値を変えない', async () => {
  const change = vi.fn()
  render(<TagPickerField value={['t1']} options={tags} accountId="a" onChange={change} />)
  const dialog = await open()
  expect(dialog.getByRole('button', { name: '選ぶ（1件）' })).toBeTruthy()
  fireEvent.click(dialog.getByRole('checkbox', { name: '来店', exact: true }))
  expect(change).not.toHaveBeenCalled()
  fireEvent.click(dialog.getByRole('button', { name: 'キャンセル' }))
  expect(change).not.toHaveBeenCalled()
  const reopened = await open()
  expect((reopened.getByRole('checkbox', { name: '来店', exact: true }) as HTMLInputElement).checked).toBe(false)
  fireEvent.change(reopened.getByRole('searchbox', { name: 'タグ名で探す' }), { target: { value: '来店' } })
  expect(reopened.queryByRole('checkbox', { name: '予約に興味', exact: true })).toBeNull()
  fireEvent.click(reopened.getByRole('checkbox', { name: '来店', exact: true }))
  fireEvent.click(reopened.getByRole('button', { name: '選ぶ（2件）' }))
  expect(change).toHaveBeenCalledWith(['t1', 't2'])
})
test('読み込み失敗を見せ、再読み込みで選べる。フォルダ取得だけ失敗したら全件から選べる', async () => {
  mocks.list.mockRejectedValueOnce(new Error('offline'))
  mocks.groups.mockRejectedValue(new Error('offline'))
  render(<TagPickerField value={[]} accountId="a" onChange={() => {}} />)
  fireEvent.click(screen.getByRole('button', { name: 'タグを付ける：選ぶ' }))
  await screen.findByText('タグを読み込めませんでした。')
  expect((screen.getByRole('button', { name: '選ぶ（0件）' }) as HTMLButtonElement).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'もう一度読み込む' }))
  await screen.findByRole('checkbox', { name: '予約に興味', exact: true })
  expect(screen.getByText('フォルダを読み込めませんでした')).toBeTruthy()
})
test('その場で作ったタグを仮選択へ足し、選ぶまで保存値を変えない', async () => {
  const change = vi.fn()
  render(<TagPickerField value={['t1']} options={tags} accountId="a" onChange={change} />)
  const dialog = await open()
  fireEvent.click(dialog.getByRole('button', { name: 'その場でタグを作る' }))
  fireEvent.change(dialog.getByRole('textbox', { name: '新しいタグの名前' }), { target: { value: '新しいタグ' } })
  fireEvent.click(dialog.getByRole('button', { name: '作る', exact: true }))
  await dialog.findByRole('checkbox', { name: '新しいタグ', exact: true })
  expect(mocks.create).toHaveBeenCalledWith({ name: '新しいタグ', groupId: null, lineAccountId: 'a' })
  expect(change).not.toHaveBeenCalled()
  fireEvent.click(dialog.getByRole('button', { name: '選ぶ（2件）' }))
  expect(change).toHaveBeenCalledWith(['t1', 'new'])
})
test('単一選択の欄は2つ目を選ぶと置き換え、閲覧のみは操作を隠す', async () => {
  const change = vi.fn()
  const { rerender } = render(<TagPickerField multiple={false} value={['t1']} options={tags} accountId="a" onChange={change} />)
  const dialog = await open()
  fireEvent.click(dialog.getByRole('checkbox', { name: '来店', exact: true }))
  fireEvent.click(dialog.getByRole('button', { name: '選ぶ（1件）' }))
  expect(change).toHaveBeenCalledWith(['t2'])
  rerender(<TapExtrasField name="ボタン1" value={{ tagIds: ['t1'], scoreChange: 10 }} tags={tags} readOnly onChange={() => {}} />)
  expect(screen.queryByRole('button')).toBeNull()
  expect(screen.getByText('予約に興味')).toBeTruthy()
  expect(screen.getByText('スコア +10点')).toBeTruthy()
})
test('閉じた追加処理を開いて整数を入力でき、外すとタグも点数も外す', async () => {
  const change = vi.fn()
  function Harness() {
    const [value, setValue] = useState({ scoreChange: null as number | null, tagIds: [] as string[] })
    return <TapExtrasField name="ボタン1" value={value} tags={tags} onChange={next => { change(next); setValue({ tagIds: next.tagIds ?? [], scoreChange: next.scoreChange ?? null }) }} />
  }
  render(<Harness />)
  fireEvent.click(screen.getByRole('button', { name: '押されたときにあわせて行うことを足す' }))
  fireEvent.change(screen.getByRole('spinbutton', { name: 'ボタン1の足すスコア' }), { target: { value: '1.5' } })
  await waitFor(() => expect(screen.getByText('足すスコアは整数で入力してください')).toBeTruthy())
  fireEvent.change(screen.getByRole('spinbutton', { name: 'ボタン1の足すスコア' }), { target: { value: '10' } })
  expect(screen.queryByText('足すスコアは整数で入力してください')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'ボタン1の追加処理を外す' }))
  expect(change).toHaveBeenLastCalledWith({ tagIds: [], scoreChange: null })
})

test('アカウントを切り替えたら前の読み込みを捨てる', async () => {
  let resolveOld!: (v: unknown) => void
  mocks.list.mockImplementationOnce(() => new Promise(resolve => { resolveOld = resolve }))
  const { rerender } = render(<TagPickerField value={[]} accountId="a" onChange={() => {}} />)
  fireEvent.click(screen.getByRole('button', { name: 'タグを付ける：選ぶ' }))
  await waitFor(() => expect(mocks.list).toHaveBeenCalledWith({ accountId: 'a' }))
  rerender(<TagPickerField value={[]} accountId="b" onChange={() => {}} />)
  fireEvent.click(screen.getByRole('button', { name: 'タグを付ける：選ぶ' }))
  await screen.findByRole('checkbox', { name: '来店', exact: true })
  resolveOld({ success: true, data: [{ id: 'old', name: '前のアカウントのタグ' }] })
  await waitFor(() => expect(screen.queryByRole('checkbox', { name: '前のアカウントのタグ' })).toBeNull())
  expect(screen.getByRole('checkbox', { name: '来店', exact: true })).toBeTruthy()
})
test('その場で作ったタグの名前は、確定後に親の候補を読み直しても残る', async () => {
  const { rerender } = render(<TagPickerField value={['t1']} options={tags} accountId="a" onChange={() => {}} />)
  const dialog = await open()
  fireEvent.click(dialog.getByRole('button', { name: 'その場でタグを作る' }))
  fireEvent.change(dialog.getByRole('textbox', { name: '新しいタグの名前' }), { target: { value: '新しいタグ' } })
  fireEvent.click(dialog.getByRole('button', { name: '作る', exact: true }))
  await dialog.findByRole('checkbox', { name: '新しいタグ', exact: true })
  fireEvent.click(dialog.getByRole('button', { name: '選ぶ（2件）' }))
  rerender(<TagPickerField value={['t1','new']} options={[...tags]} accountId="a" onChange={() => {}} />)
  expect(screen.getByText('新しいタグ')).toBeTruthy()
})

test('統括からその場で作るタグは、選んだフォルダの店舗に所属する', async () => {
  mocks.list.mockResolvedValue({ success: true, data: tags.map((tag, i) => ({ ...tag, lineAccountId: i ? 'b' : 'a' })) })
  mocks.groups.mockResolvedValue({ success: true, data: [{ id: 'g1', name: '興味', color: '#087a3e', accountId: 'a' }] })
  render(<TagPickerField value={['t1']} options={tags} accountId={null} onChange={() => {}} />)
  const dialog = await open()
  fireEvent.click(dialog.getByRole('button', { name: 'その場でタグを作る' }))
  fireEvent.change(dialog.getByRole('textbox', { name: '新しいタグの名前' }), { target: { value: '新しいタグ' } })
  fireEvent.click(dialog.getByRole('button', { name: '作る', exact: true }))
  expect(screen.getByText('タグを作る店舗を決めるため、左の店舗のフォルダを選んでください。')).toBeTruthy()
  fireEvent.click(dialog.getByRole('button', { name: /興味/ }))
  fireEvent.click(dialog.getByRole('button', { name: '作る', exact: true }))
  await waitFor(() => expect(mocks.create).toHaveBeenCalledWith({ name: '新しいタグ', groupId: 'g1', lineAccountId: 'a' }))
})
