import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { waitlistFixture, futureSlot } from '../test-utils/waitlist-fixture.js';
import type { SqliteD1 } from '../test-utils/d1-sqlite.js';
import { promoteBookingWaitlist, finishExpiredWaitlists, waitlistHoldMinutes, dispatchWaitlistInvites } from './booking-waitlist.js';
import type { Env } from '../index.js';
const send = vi.hoisted(() => vi.fn(async (_env: unknown, _input: Record<string, unknown>) => true)); vi.mock('./booking-automatic-line.js', () => ({ sendAutomaticBookingLine: send }));
let test: SqliteD1, slot: string;
beforeEach(() => { test = waitlistFixture(); slot = futureSlot(); send.mockReset(); send.mockResolvedValue(true); }); afterEach(() => test.raw.close());
function add(id: string, friend = 'f0', start = slot, staff = 's') { test.raw.prepare(`INSERT INTO booking_waitlist(id,line_account_id,staff_id,menu_id,starts_at,friend_id,identity_key) VALUES(?,'a',?,'m',?,?,?)`).run(id, staff, start, friend, 'friend:' + friend); }
function promote(staff = 's', start = slot) { return promoteBookingWaitlist(test.db, { lineAccountId: 'a', staffId: staff, startsAt: start }); }
function booking(id: string, friend: string, waitlistId: string | null = null, staff = 's', start = slot) { test.raw.prepare(`INSERT INTO bookings(id,line_account_id,friend_id,staff_id,menu_id,starts_at,ends_at,block_ends_at,status,price_at_booking,requested_at,waitlist_entry_id) VALUES(?,'a',?,?,'m',?,?,?,'confirmed',0,?,?)`).run(id, friend, staff, start, new Date(Date.parse(start) + 3600000).toISOString(), new Date(Date.parse(start) + 3600000).toISOString(), new Date().toISOString(), waitlistId); }
describe('人のキャンセル待ち・承認済みの順送り', () => {
  it('先頭だけ30分仮押さえし、ほかの人が枠を取れない', async () => { add('w0'); add('w1', 'f1'); expect((await promote()).promoted).toBe(true); expect((await promote()).promoted).toBe(false); expect(test.raw.prepare('SELECT hold_minutes FROM booking_waitlist WHERE id=?').get('w0')).toMatchObject({ hold_minutes: 30 }); expect(() => booking('steal', 'f2')).toThrow('waitlist_hold_conflict'); });
  it('同時受付数2で空いた2人分だけ先着順に案内する', async () => { test.raw.exec("UPDATE menus SET concurrent_capacity=2 WHERE id='m'"); add('w0'); add('w1', 'f1'); add('w2', 'f2'); expect((await promote()).promoted).toBe(true); expect((await promote()).promoted).toBe(true); expect((await promote()).promoted).toBe(false); expect(test.raw.prepare("SELECT COUNT(*) n FROM booking_waitlist WHERE status='invited'").get()).toMatchObject({ n: 2 }); });
  it('期限切れを終わりにし、登録順を変えず次の人へ', async () => { add('w0'); add('w1', 'f1'); await promote(); test.raw.prepare("UPDATE booking_waitlist SET hold_expires_at=? WHERE id='w0'").run(new Date(Date.now() - 1000).toISOString()); await promote(); expect(test.raw.prepare("SELECT status,finish_reason FROM booking_waitlist WHERE id='w0'").get()).toMatchObject({ status: 'finished', finish_reason: 'offer_expired' }); expect(test.raw.prepare("SELECT status FROM booking_waitlist WHERE id='w1'").get()).toMatchObject({ status: 'invited' }); });
  it('本人の予約確定と待ちの変換は同じDB書き込み。別人・別枠は拒否', async () => { add('w0'); await promote(); expect(() => booking('wrong', 'f1', 'w0')).toThrow('waitlist_hold_conflict'); booking('right', 'f0', 'w0'); expect(test.raw.prepare("SELECT status FROM booking_waitlist WHERE id='w0'").get()).toMatchObject({ status: 'converted' }); expect(() => booking('duplicate', 'f0', 'w0')).toThrow(); });
  it('予約の時刻変更でも他の人の仮押さえへ入れない', async () => { add('w0'); await promote(); const later = new Date(Date.parse(slot) + 7200000).toISOString(); booking('b1', 'f1', null, 's', later); expect(() => test.raw.prepare('UPDATE bookings SET starts_at=?,ends_at=?,block_ends_at=? WHERE id=?').run(slot, new Date(Date.parse(slot) + 3600000).toISOString(), new Date(Date.parse(slot) + 3600000).toISOString(), 'b1')).toThrow('waitlist_hold_conflict'); });
  it('変換済みの予約はその後の時刻変更ができる', async () => { add('w0'); await promote(); booking('right', 'f0', 'w0'); const later = new Date(Date.parse(slot) + 7200000).toISOString(); expect(() => test.raw.prepare("UPDATE bookings SET starts_at=?,ends_at=?,block_ends_at=? WHERE id='right'").run(later, new Date(Date.parse(later) + 3600000).toISOString(), new Date(Date.parse(later) + 3600000).toISOString())).not.toThrow(); });
  it('開始まで2時間を切ると10分。2時間ちょうどは30分', () => { const now = new Date(); expect(waitlistHoldMinutes(new Date(now.getTime() + 119 * 60000).toISOString(), now)).toBe(10); expect(waitlistHoldMinutes(new Date(now.getTime() + 120 * 60000).toISOString(), now)).toBe(30); });
  it('1時間前の受付締切と同時3件をDBでも守る', () => { const near = new Date(Date.now() + 59 * 60000).toISOString(); expect(() => add('closed', 'f0', near)).toThrow('waitlist_registration_closed'); add('one'); add('two', 'f0', futureSlot(3)); add('three', 'f0', futureSlot(4)); expect(() => add('four', 'f0', futureSlot(5))).toThrow('waitlist_limit'); });
  it('受付を締めた待ちは終わりにする', async () => { add('w0'); await finishExpiredWaitlists(test.db, 'a', new Date(Date.parse(slot) - 59 * 60000)); expect(test.raw.prepare("SELECT status FROM booking_waitlist WHERE id='w0'").get()).toMatchObject({ status: 'finished' }); });
  it('店の席数をスタッフ横断の仮押さえにも適用する', async () => { test.raw.exec('UPDATE booking_business_hours SET capacity=1'); add('w0'); add('w1', 'f1', slot, 'other'); await promote(); expect((await promote('other')).promoted).toBe(false); expect(() => booking('steal', 'f2', null, 'other')).toThrow('waitlist_hold_conflict'); });
  it('設備を別スタッフの予約と共有し、仮押さえ時点の設備を保護する', async () => { test.raw.exec("INSERT INTO booking_resources(id,line_account_id,name,resource_type,capacity) VALUES('r','a','試験設備','room',1);INSERT INTO booking_menu_resources(menu_id,resource_id,quantity) VALUES('m','r',1)"); add('w0'); await promote(); expect(() => booking('steal', 'f1', null, 'other')).toThrow('waitlist_hold_conflict'); });
  it('停止で送らない場合は未送信として残し、同じ再送キーで回収する', async () => { add('w0'); await promote(); const env = { DB: test.db, LIFF_URL: 'https://liff.example.test' } as Env['Bindings']; send.mockResolvedValue(false); await dispatchWaitlistInvites(env, 'a'); expect(test.raw.prepare("SELECT notified_at FROM booking_waitlist WHERE id='w0'").get()).toMatchObject({ notified_at: null }); test.raw.exec('UPDATE booking_waitlist SET notification_claim_until=NULL'); send.mockResolvedValue(true); await dispatchWaitlistInvites(env, 'a'); expect(send.mock.calls).toHaveLength(2); expect(send.mock.calls[0][1].retryKey).toBe(send.mock.calls[1][1].retryKey); });
  it('同時の通知回収は1通にし、本人用の予約・見送りリンクを付ける', async () => { add('w0'); await promote(); const env = { DB: test.db, LIFF_URL: 'https://liff.example.test' } as Env['Bindings']; await Promise.all([dispatchWaitlistInvites(env, 'a'), dispatchWaitlistInvites(env, 'a')]); expect(send).toHaveBeenCalledTimes(1); expect(send.mock.calls[0][1].text).toContain('action=decline'); });
  it('待ちが空なら何も案内しない', async () => { expect(await promote()).toMatchObject({ promoted: false, reason: 'empty' }); });
});
