-- オーナー承認 2026-10-10 / PLAN §2: 座席図・結合卓。
CREATE TABLE rt_floors (
 id TEXT PRIMARY KEY, store_id TEXT NOT NULL REFERENCES rt_stores(id), name TEXT NOT NULL,
 width REAL NOT NULL DEFAULT 1000 CHECK(width>0), height REAL NOT NULL DEFAULT 700 CHECK(height>0),
 outline_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(outline_json)),
 fixtures_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(fixtures_json)),
 version INTEGER NOT NULL DEFAULT 1, UNIQUE(store_id,name)
);
ALTER TABLE rt_tables ADD COLUMN floor_id TEXT REFERENCES rt_floors(id);
ALTER TABLE rt_tables ADD COLUMN shape TEXT NOT NULL DEFAULT 'rectangle' CHECK(shape IN ('rectangle','circle','long','counter','sofa'));
ALTER TABLE rt_tables ADD COLUMN width REAL NOT NULL DEFAULT 80 CHECK(width>0);
ALTER TABLE rt_tables ADD COLUMN height REAL NOT NULL DEFAULT 64 CHECK(height>0);
ALTER TABLE rt_tables ADD COLUMN rotation REAL NOT NULL DEFAULT 0;
INSERT INTO rt_floors(id,store_id,name) SELECT 'floor-'||id,id,'1階' FROM rt_stores;
UPDATE rt_tables SET floor_id='floor-'||store_id;
-- 旧マス目の場所を図面の寸法へ移す（卓・予約のIDは保持する）。
UPDATE rt_tables SET floor_x=40+floor_x*120,floor_y=40+floor_y*100 WHERE floor_x<=20 AND floor_y<=20;
UPDATE rt_floors SET width=MAX(width,COALESCE((SELECT MAX(floor_x+width+40) FROM rt_tables WHERE floor_id=rt_floors.id),width)),height=MAX(height,COALESCE((SELECT MAX(floor_y+height+40) FROM rt_tables WHERE floor_id=rt_floors.id),height));
CREATE TABLE rt_reservation_table_links (
 reservation_id TEXT NOT NULL REFERENCES rt_reservations(id) ON DELETE CASCADE,
 table_id TEXT NOT NULL REFERENCES rt_tables(id), PRIMARY KEY(reservation_id,table_id)
);
CREATE TABLE rt_seat_waitlist_table_links (
 waitlist_id TEXT NOT NULL REFERENCES rt_seat_waitlist(id) ON DELETE CASCADE,
 table_id TEXT NOT NULL REFERENCES rt_tables(id), PRIMARY KEY(waitlist_id,table_id)
);
CREATE INDEX rt_reserved_table ON rt_reservation_table_links(table_id,reservation_id);
CREATE INDEX rt_waiting_table ON rt_seat_waitlist_table_links(table_id,waitlist_id);
INSERT INTO rt_reservation_table_links SELECT id,table_id FROM rt_reservations WHERE table_id IS NOT NULL;
INSERT INTO rt_seat_waitlist_table_links SELECT id,table_id FROM rt_seat_waitlist WHERE table_id IS NOT NULL;
-- 既存通知は注意・来店の改版では失わない。日時・人数・取消の変更のみ古い結果を無効にする。
ALTER TABLE rt_customer_notice_outbox ADD COLUMN valid INTEGER NOT NULL DEFAULT 1 CHECK(valid IN(0,1));
CREATE TRIGGER rt_reservation_version AFTER UPDATE ON rt_reservations WHEN NEW.customer_version=OLD.customer_version AND ( NEW.customer_name IS NOT OLD.customer_name OR NEW.customer_phone IS NOT OLD.customer_phone OR NEW.guest_count IS NOT OLD.guest_count OR NEW.starts_at IS NOT OLD.starts_at OR NEW.ends_at IS NOT OLD.ends_at OR NEW.table_id IS NOT OLD.table_id OR NEW.course_id IS NOT OLD.course_id OR NEW.status IS NOT OLD.status OR NEW.allergy_note IS NOT OLD.allergy_note OR NEW.note IS NOT OLD.note OR NEW.hold_expires_at IS NOT OLD.hold_expires_at) BEGIN UPDATE rt_reservations SET customer_version=OLD.customer_version+1 WHERE id=NEW.id; END;
CREATE TRIGGER rt_notice_booking_change AFTER UPDATE OF starts_at,ends_at,guest_count,status ON rt_reservations WHEN NEW.starts_at IS NOT OLD.starts_at OR NEW.ends_at IS NOT OLD.ends_at OR NEW.guest_count IS NOT OLD.guest_count OR (NEW.status IN('cancelled','no_show') AND NEW.status IS NOT OLD.status) BEGIN UPDATE rt_customer_notice_outbox SET valid=0 WHERE reservation_id=NEW.id AND sent_at IS NULL; END;
CREATE TRIGGER rt_reservations_linked_insert AFTER INSERT ON rt_reservations BEGIN DELETE FROM rt_reservation_table_links WHERE reservation_id=NEW.id; INSERT INTO rt_reservation_table_links(reservation_id,table_id) SELECT NEW.id,t.id FROM rt_tables t JOIN rt_tables main ON main.id=NEW.table_id WHERE t.store_id=NEW.store_id AND (t.id=main.id OR (NEW.guest_count>main.max_capacity AND main.join_group IS NOT NULL AND t.join_group=main.join_group)); END;
CREATE TRIGGER rt_reservations_linked_update AFTER UPDATE OF table_id,guest_count ON rt_reservations WHEN NEW.table_id IS NOT OLD.table_id OR NEW.guest_count IS NOT OLD.guest_count BEGIN DELETE FROM rt_reservation_table_links WHERE reservation_id=NEW.id; INSERT INTO rt_reservation_table_links(reservation_id,table_id) SELECT NEW.id,t.id FROM rt_tables t JOIN rt_tables main ON main.id=NEW.table_id WHERE t.store_id=NEW.store_id AND (t.id=main.id OR (NEW.guest_count>main.max_capacity AND main.join_group IS NOT NULL AND t.join_group=main.join_group)); END;
CREATE TRIGGER rt_reservations_linked_time_update BEFORE UPDATE OF starts_at,ends_at,status,hold_expires_at ON rt_reservations WHEN NEW.table_id IS OLD.table_id AND NEW.guest_count=OLD.guest_count AND NEW.status NOT IN('cancelled','no_show') AND (NEW.status<>'pending' OR NEW.hold_expires_at IS NULL OR julianday(NEW.hold_expires_at)>julianday('now')) AND (EXISTS(SELECT 1 FROM rt_reservations r JOIN rt_reservation_table_links l ON l.reservation_id=r.id WHERE r.store_id=NEW.store_id AND r.id<>NEW.id AND r.status NOT IN('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR julianday(r.hold_expires_at)>julianday('now')) AND l.table_id IN (SELECT table_id FROM rt_reservation_table_links WHERE reservation_id=NEW.id) AND julianday(r.starts_at)<julianday(NEW.ends_at) AND julianday(r.ends_at)>julianday(NEW.starts_at)) OR EXISTS(SELECT 1 FROM rt_seat_waitlist w JOIN rt_seat_waitlist_table_links l ON l.waitlist_id=w.id WHERE w.store_id=NEW.store_id AND w.status='invited' AND julianday(w.hold_expires_at)>julianday('now') AND l.table_id IN (SELECT table_id FROM rt_reservation_table_links WHERE reservation_id=NEW.id) AND julianday(w.starts_at)<julianday(NEW.ends_at) AND julianday(COALESCE(w.ends_at,datetime(w.starts_at,'+120 minutes')))>julianday(NEW.starts_at))) BEGIN SELECT RAISE(ABORT,'restaurant_table_conflict'); END;
CREATE TRIGGER rt_reservation_table_links_guard BEFORE INSERT ON rt_reservation_table_links WHEN EXISTS(SELECT 1 FROM rt_reservations r WHERE r.id=NEW.reservation_id AND r.status NOT IN('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR julianday(r.hold_expires_at)>julianday('now')) AND ( NOT EXISTS(SELECT 1 FROM rt_tables t WHERE t.id=NEW.table_id AND t.store_id=r.store_id AND t.is_active=1) OR EXISTS(SELECT 1 FROM rt_reservations other JOIN rt_reservation_table_links l ON l.reservation_id=other.id WHERE other.id<>r.id AND l.table_id=NEW.table_id AND other.status NOT IN('cancelled','no_show') AND (other.status<>'pending' OR other.hold_expires_at IS NULL OR julianday(other.hold_expires_at)>julianday('now')) AND julianday(other.starts_at)<julianday(r.ends_at) AND julianday(other.ends_at)>julianday(r.starts_at)) OR EXISTS(SELECT 1 FROM rt_seat_waitlist other JOIN rt_seat_waitlist_table_links l ON l.waitlist_id=other.id WHERE l.table_id=NEW.table_id AND other.status='invited' AND julianday(other.hold_expires_at)>julianday('now') AND julianday(other.starts_at)<julianday(r.ends_at) AND julianday(COALESCE(other.ends_at,datetime(other.starts_at,'+120 minutes')))>julianday(r.starts_at)) OR EXISTS(SELECT 1 FROM rt_closures c,json_each(c.periods_json) p WHERE c.store_id=r.store_id AND c.archived_at IS NULL AND (json_array_length(c.table_ids_json)=0 OR NEW.table_id IN(SELECT value FROM json_each(c.table_ids_json))) AND julianday(json_extract(p.value,'$.startsAt'))<julianday(r.ends_at) AND julianday(json_extract(p.value,'$.endsAt'))>julianday(r.starts_at)) )) BEGIN SELECT RAISE(ABORT,'restaurant_table_conflict'); END;
CREATE TRIGGER rt_seat_waitlist_linked_insert AFTER INSERT ON rt_seat_waitlist BEGIN DELETE FROM rt_seat_waitlist_table_links WHERE waitlist_id=NEW.id; INSERT INTO rt_seat_waitlist_table_links(waitlist_id,table_id) SELECT NEW.id,t.id FROM rt_tables t JOIN rt_tables main ON main.id=NEW.table_id WHERE t.store_id=NEW.store_id AND (t.id=main.id OR (NEW.guest_count>main.max_capacity AND main.join_group IS NOT NULL AND t.join_group=main.join_group)); END;
CREATE TRIGGER rt_seat_waitlist_linked_update AFTER UPDATE OF table_id,guest_count ON rt_seat_waitlist WHEN NEW.table_id IS NOT OLD.table_id OR NEW.guest_count IS NOT OLD.guest_count BEGIN DELETE FROM rt_seat_waitlist_table_links WHERE waitlist_id=NEW.id; INSERT INTO rt_seat_waitlist_table_links(waitlist_id,table_id) SELECT NEW.id,t.id FROM rt_tables t JOIN rt_tables main ON main.id=NEW.table_id WHERE t.store_id=NEW.store_id AND (t.id=main.id OR (NEW.guest_count>main.max_capacity AND main.join_group IS NOT NULL AND t.join_group=main.join_group)); END;
CREATE TRIGGER rt_seat_waitlist_linked_time_update BEFORE UPDATE OF starts_at,ends_at,status,hold_expires_at ON rt_seat_waitlist WHEN NEW.table_id IS OLD.table_id AND NEW.guest_count=OLD.guest_count AND NEW.status='invited' AND julianday(NEW.hold_expires_at)>julianday('now') AND (EXISTS(SELECT 1 FROM rt_reservations r JOIN rt_reservation_table_links l ON l.reservation_id=r.id WHERE r.store_id=NEW.store_id AND r.status NOT IN('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR julianday(r.hold_expires_at)>julianday('now')) AND l.table_id IN (SELECT table_id FROM rt_seat_waitlist_table_links WHERE waitlist_id=NEW.id) AND julianday(r.starts_at)<julianday(NEW.ends_at) AND julianday(r.ends_at)>julianday(NEW.starts_at)) OR EXISTS(SELECT 1 FROM rt_seat_waitlist w JOIN rt_seat_waitlist_table_links l ON l.waitlist_id=w.id WHERE w.store_id=NEW.store_id AND w.id<>NEW.id AND w.status='invited' AND julianday(w.hold_expires_at)>julianday('now') AND l.table_id IN (SELECT table_id FROM rt_seat_waitlist_table_links WHERE waitlist_id=NEW.id) AND julianday(w.starts_at)<julianday(NEW.ends_at) AND julianday(COALESCE(w.ends_at,datetime(w.starts_at,'+120 minutes')))>julianday(NEW.starts_at))) BEGIN SELECT RAISE(ABORT,'restaurant_table_conflict'); END;
CREATE TRIGGER rt_seat_waitlist_table_links_guard BEFORE INSERT ON rt_seat_waitlist_table_links WHEN EXISTS(SELECT 1 FROM rt_seat_waitlist w WHERE w.id=NEW.waitlist_id AND w.status='invited' AND julianday(w.hold_expires_at)>julianday('now') AND ( NOT EXISTS(SELECT 1 FROM rt_tables t WHERE t.id=NEW.table_id AND t.store_id=w.store_id AND t.is_active=1) OR EXISTS(SELECT 1 FROM rt_reservations other JOIN rt_reservation_table_links l ON l.reservation_id=other.id WHERE l.table_id=NEW.table_id AND other.status NOT IN('cancelled','no_show') AND (other.status<>'pending' OR other.hold_expires_at IS NULL OR julianday(other.hold_expires_at)>julianday('now')) AND julianday(other.starts_at)<julianday(w.ends_at) AND julianday(other.ends_at)>julianday(w.starts_at)) OR EXISTS(SELECT 1 FROM rt_seat_waitlist other JOIN rt_seat_waitlist_table_links l ON l.waitlist_id=other.id WHERE other.id<>w.id AND l.table_id=NEW.table_id AND other.status='invited' AND julianday(other.hold_expires_at)>julianday('now') AND julianday(other.starts_at)<julianday(w.ends_at) AND julianday(COALESCE(other.ends_at,datetime(other.starts_at,'+120 minutes')))>julianday(w.starts_at)) OR EXISTS(SELECT 1 FROM rt_closures c,json_each(c.periods_json) p WHERE c.store_id=w.store_id AND c.archived_at IS NULL AND (json_array_length(c.table_ids_json)=0 OR NEW.table_id IN(SELECT value FROM json_each(c.table_ids_json))) AND julianday(json_extract(p.value,'$.startsAt'))<julianday(w.ends_at) AND julianday(json_extract(p.value,'$.endsAt'))>julianday(w.starts_at)) )) BEGIN SELECT RAISE(ABORT,'restaurant_table_conflict'); END;
DROP VIEW rt_inventory_occupancy;
CREATE VIEW rt_inventory_occupancy AS SELECT i.*,
 COALESCE((SELECT SUM(r.guest_count) FROM rt_reservations r WHERE r.store_id=i.store_id
  AND r.status NOT IN ('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR datetime(r.hold_expires_at)>datetime('now'))
  AND datetime(r.starts_at)<datetime(i.starts_at, '+' || i.slot_minutes || ' minutes') AND datetime(r.ends_at)>datetime(i.starts_at)),0) AS guest_count,
 COALESCE((SELECT SUM(t.max_capacity) FROM rt_tables t WHERE t.store_id=i.store_id AND t.is_active=1
  AND EXISTS (SELECT 1 FROM rt_reservations r WHERE EXISTS(SELECT 1 FROM rt_reservation_table_links l WHERE l.reservation_id=r.id AND l.table_id=t.id) AND r.store_id=i.store_id
   AND r.status NOT IN ('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR datetime(r.hold_expires_at)>datetime('now'))
   AND datetime(r.starts_at)<datetime(i.starts_at, '+' || i.slot_minutes || ' minutes') AND datetime(r.ends_at)>datetime(i.starts_at))),0) AS occupied_seats,
 (SELECT json_group_array(t.id) FROM rt_tables t WHERE t.store_id=i.store_id AND t.is_active=1
  AND EXISTS (SELECT 1 FROM rt_reservations r WHERE EXISTS(SELECT 1 FROM rt_reservation_table_links l WHERE l.reservation_id=r.id AND l.table_id=t.id) AND r.store_id=i.store_id
   AND r.status NOT IN ('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR datetime(r.hold_expires_at)>datetime('now'))
   AND datetime(r.starts_at)<datetime(i.starts_at, '+' || i.slot_minutes || ' minutes') AND datetime(r.ends_at)>datetime(i.starts_at))) AS occupied_table_ids_json,
 COALESCE((SELECT SUM(r.guest_count) FROM rt_reservations r WHERE r.store_id=i.store_id AND r.table_id IS NULL
  AND r.status NOT IN ('cancelled','no_show') AND (r.status<>'pending' OR r.hold_expires_at IS NULL OR datetime(r.hold_expires_at)>datetime('now'))
  AND datetime(r.starts_at)<datetime(i.starts_at, '+' || i.slot_minutes || ' minutes') AND datetime(r.ends_at)>datetime(i.starts_at)),0) AS unassigned_guests
 FROM rt_inventory_slots i;

-- 新しく追加した店舗・卓も同じ階へ置く。既存の座標は変えない。
CREATE TRIGGER rt_floor_new_store AFTER INSERT ON rt_stores BEGIN INSERT INTO rt_floors(id,store_id,name) VALUES('floor-'||NEW.id,NEW.id,'1階'); END;
CREATE TRIGGER rt_floor_new_table AFTER INSERT ON rt_tables WHEN NEW.floor_id IS NULL BEGIN UPDATE rt_tables SET floor_id='floor-'||NEW.store_id WHERE id=NEW.id; END;
