-- オーナー承認 2026-10-10 / PLAN 仮632。最小の空き番号629。
-- 元予約と同一トランザクションで記録。古い予約への推測の補充はしない。
CREATE TABLE rt_reservation_events (
 id TEXT PRIMARY KEY, reservation_id TEXT REFERENCES rt_reservations(id),
 store_id TEXT NOT NULL REFERENCES rt_stores(id), event_type TEXT NOT NULL,
 reservation_version INTEGER NOT NULL, occurred_at TEXT NOT NULL, request_id TEXT NOT NULL,
 line_account_id TEXT, friend_id TEXT, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),
 UNIQUE(reservation_id,reservation_version,event_type)
);
CREATE TABLE rt_reservation_event_receipts (
 event_id TEXT NOT NULL REFERENCES rt_reservation_events(id), consumer_key TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN('pending','running','succeeded','failed')),
 attempt_count INTEGER NOT NULL DEFAULT 0, lease_until TEXT, lease_owner TEXT, next_attempt_at TEXT, result_ref TEXT,
 PRIMARY KEY(event_id,consumer_key)
);
CREATE INDEX rt_event_pending ON rt_reservation_event_receipts(status,next_attempt_at);
CREATE TRIGGER rt_event_receipts AFTER INSERT ON rt_reservation_events BEGIN INSERT INTO rt_reservation_event_receipts(event_id,consumer_key) VALUES(NEW.id,'event_bus'),(NEW.id,'mileage'); INSERT INTO rt_reservation_event_receipts(event_id,consumer_key) SELECT NEW.id,'visit_stamp_queue' WHERE NEW.event_type IN('restaurant.arrived','restaurant.arrival_undone'); END;
CREATE TRIGGER rt_reservation_event_insert AFTER INSERT ON rt_reservations WHEN NEW.status IN('confirmed','seated','visited') BEGIN INSERT OR IGNORE INTO rt_reservation_events(id,reservation_id,store_id,event_type,reservation_version,occurred_at,request_id,line_account_id,friend_id,payload_json) SELECT 'rt:'||NEW.id||':'||NEW.customer_version||':restaurant.reservation.created',NEW.id,NEW.store_id,'restaurant.reservation.created',NEW.customer_version,strftime('%Y-%m-%dT%H:%M:%fZ','now'),NEW.id||':'||NEW.customer_version,s.line_account_id, (SELECT id FROM friends WHERE line_account_id=s.line_account_id AND line_user_id=NEW.line_uid), json_object('reservationId',NEW.id,'storeId',NEW.store_id,'startsAt',NEW.starts_at,'endsAt',NEW.ends_at,'status',NEW.status,'guestCount',NEW.guest_count) FROM rt_stores s WHERE s.id=NEW.store_id; END;
CREATE TRIGGER rt_reservation_event_update AFTER UPDATE OF customer_version ON rt_reservations WHEN NEW.customer_version>OLD.customer_version BEGIN INSERT OR IGNORE INTO rt_reservation_events(id,reservation_id,store_id,event_type,reservation_version,occurred_at,request_id,line_account_id,friend_id,payload_json) SELECT 'rt:'||NEW.id||':'||NEW.customer_version||':'|| CASE WHEN NEW.departed_at IS NOT OLD.departed_at THEN CASE WHEN NEW.departed_at IS NULL THEN 'restaurant.departure_undone' ELSE 'restaurant.departed' END WHEN NEW.status IN('cancelled','no_show') AND NEW.status IS NOT OLD.status THEN 'restaurant.reservation.cancelled' WHEN NEW.status='visited' AND OLD.status<>'visited' THEN 'restaurant.arrived' WHEN OLD.status IN('visited','seated') AND NEW.status='confirmed' THEN 'restaurant.arrival_undone' WHEN OLD.status='pending' AND NEW.status='confirmed' THEN 'restaurant.reservation.created' ELSE 'restaurant.reservation.changed' END, NEW.id,NEW.store_id, CASE WHEN NEW.departed_at IS NOT OLD.departed_at THEN CASE WHEN NEW.departed_at IS NULL THEN 'restaurant.departure_undone' ELSE 'restaurant.departed' END WHEN NEW.status IN('cancelled','no_show') AND NEW.status IS NOT OLD.status THEN 'restaurant.reservation.cancelled' WHEN NEW.status='visited' AND OLD.status<>'visited' THEN 'restaurant.arrived' WHEN OLD.status IN('visited','seated') AND NEW.status='confirmed' THEN 'restaurant.arrival_undone' WHEN OLD.status='pending' AND NEW.status='confirmed' THEN 'restaurant.reservation.created' ELSE 'restaurant.reservation.changed' END, NEW.customer_version,strftime('%Y-%m-%dT%H:%M:%fZ','now'),NEW.id||':'||NEW.customer_version,s.line_account_id, (SELECT id FROM friends WHERE line_account_id=s.line_account_id AND line_user_id=NEW.line_uid), json_object('reservationId',NEW.id,'storeId',NEW.store_id,'startsAt',NEW.starts_at,'endsAt',NEW.ends_at,'status',NEW.status,'guestCount',NEW.guest_count,'departedAt',NEW.departed_at,'previousVersion',OLD.customer_version, 'scheduleChanged',NEW.starts_at IS NOT OLD.starts_at OR NEW.ends_at IS NOT OLD.ends_at OR NEW.guest_count IS NOT OLD.guest_count) FROM rt_stores s WHERE s.id=NEW.store_id; END;
CREATE TRIGGER rt_waitlist_invite_event AFTER UPDATE OF status ON rt_seat_waitlist WHEN NEW.status='invited' AND OLD.status='waiting' BEGIN INSERT OR IGNORE INTO rt_reservation_events(id,store_id,event_type,reservation_version,occurred_at,request_id,line_account_id,friend_id,payload_json) SELECT 'rt-waitlist:'||NEW.id||':'||NEW.notification_retry_key,NEW.store_id,'restaurant.waitlist.invited',0,NEW.invited_at,NEW.notification_retry_key,s.line_account_id, (SELECT id FROM friends WHERE line_account_id=s.line_account_id AND line_user_id=NEW.line_uid), json_object('waitlistId',NEW.id,'storeId',NEW.store_id,'startsAt',NEW.starts_at,'holdExpiresAt',NEW.hold_expires_at) FROM rt_stores s WHERE s.id=NEW.store_id; END;
CREATE TRIGGER rt_walkin_arrival_event AFTER INSERT ON rt_seat_visit_marks WHEN NEW.kind='visited' AND NEW.undone_at IS NULL BEGIN INSERT OR IGNORE INTO rt_reservation_events(id,reservation_id,store_id,event_type,reservation_version,occurred_at,request_id,line_account_id,friend_id,payload_json) SELECT 'rt:'||r.id||':'||r.customer_version||':restaurant.arrived',r.id,r.store_id,'restaurant.arrived',r.customer_version,NEW.marked_at,COALESCE(NEW.request_id,NEW.id),s.line_account_id,(SELECT id FROM friends WHERE line_account_id=s.line_account_id AND line_user_id=r.line_uid),json_object('reservationId',r.id,'storeId',r.store_id,'startsAt',r.starts_at,'endsAt',r.ends_at,'status',r.status,'guestCount',r.guest_count) FROM rt_reservations r JOIN rt_stores s ON s.id=r.store_id WHERE r.id=NEW.reservation_id AND r.status IN('visited','seated'); END;
